spring:
  application:
    name: backend

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

app:
  jwt:
    access-token-expiration-seconds: 3600
  kakao:
    authorization-url: https://kauth.kakao.com/oauth/authorize
    token-url: https://kauth.kakao.com/oauth/token
    user-info-url: https://kapi.kakao.com/v2/user/me
