spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/plavor_local
    username: plavor
    password: plavor_password

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

management:
  endpoint:
    health:
      show-details: always
